apiVersion: v1
kind: Namespace
metadata:
  name: mcpspy
  labels:
    app.kubernetes.io/name: mcpspy
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcpspy
  namespace: mcpspy
  labels:
    app.kubernetes.io/name: mcpspy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcpspy
  labels:
    app.kubernetes.io/name: mcpspy
rules:
- apiGroups: [""]  # "" indicates the core API group
  resources: ["pods", "namespaces", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
    - replicasets
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcpspy
  labels:
    app.kubernetes.io/name: mcpspy
subjects:
- kind: ServiceAccount
  name: mcpspy
  namespace: mcpspy
roleRef:
  kind: ClusterRole
  name: mcpspy
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mcpspy
  namespace: mcpspy
  labels:
    app.kubernetes.io/name: mcpspy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mcpspy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mcpspy
    spec:
      serviceAccountName: mcpspy
      hostPID: true  # Required to monitor processes across the node
      containers:
      - name: mcpspy
        image: ghcr.io/alex-ilgayev/mcpspy:v0.0.3
        imagePullPolicy: Always
        securityContext:
          privileged: true  # Required for eBPF access
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          exec:
            command: ["/bin/sh", "-c", "pgrep mcpspy"]
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["/bin/sh", "-c", "pgrep mcpspy"]
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: output
          mountPath: /output
        command:
        - "/app/mcpspy"
        - "-o"
        - "/output/mcpspy.jsonl"
      volumes:
      - name: output
        emptyDir: {}
---
